[package]
name = "followos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# 解决对 eh_personality 的依赖。
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
